### ISSUE TITLE
Move to Multiformats?

### ISSUE THREAD

**Issue by RichardLitt** [multiformats/rust-multiaddr#10]
Hey @dignifiedquire - want to move this to the multiformats org? 

Tracking issue, here: https://github.com/multiformats/multiformats/issues/4.

**Comment by dignifiedquire** [comment]
Sure

**Comment by RichardLitt** [comment]
Sweet!

**Comment by dignifiedquire** [comment]
@RichardLitt moved but gh permissions through me out of being able to administrate the repo :(

**Comment by RichardLitt** [comment]
Fixed. You should have those now.

**Comment by dignifiedquire** [comment]
Thanks, leaving this open to track changes in cargo and the readme and publishing a fresh version

**Comment by dignifiedquire** [comment]
Done
