### ISSUE TITLE
Re-export libp2p_identity::PeerId?

### ISSUE THREAD

**Issue by dav1do** [multiformats/rust-multiaddr#107]
While updating a project with dependencies on `multiaddr` and `multihash`, I noticed that `libp2p_identity::PeerId` isn't re-exported but is in two public interfaces: [MultiAddr::with_p2p](https://github.com/multiformats/rust-multiaddr/blob/38d3a5727164f2c2e60385c9fa2903f259c48758/src/lib.rs#L136) and [Protocol::P2p](https://github.com/multiformats/rust-multiaddr/blob/38d3a5727164f2c2e60385c9fa2903f259c48758/src/protocol.rs#L102). Any objections to a re-export (or a wrapper tuple struct with `Deref`/`DerefMut`)? I'm happy to make a PR, but I figured I'd ask first as it has dependency/API ramifications.

I know the libp2p-identity crate is small so I could add it, but it'd be nice to have this library be self contained. I have an API that looks like a tiny bit of IPFS, which is why I want address info without actually pulling in libp2p proper.

**Comment by thomaseizinger** [comment]
A re-export of `PeerId` seems fine to me, yes :)

**Comment by jxs** [comment]
addressed with #108
