### ISSUE TITLE
Replace `Arc<Vec<u8>>` with `Arc<[u8]>`

### ISSUE THREAD

**Issue by nazar-pc** [multiformats/rust-multiaddr#117]
Dual indirection is completely unnecessary:
https://github.com/multiformats/rust-multiaddr/blob/469b0deb9a64554c11e1d2227c78fe7c6c769aa7/src/lib.rs#L44-L46

**Comment by jxs** [comment]
Hi Nazar, thanks. Would you like to submit a PR addressing it?
