### ISSUE TITLE
Links to the doc are broken

### ISSUE THREAD

**Issue by ProgVal** [multiformats/rust-multiaddr#13]
Links to the doc in the Github project description and the README are https://dignifiedquire.github.io/rust-multiaddr/multiaddr/struct.Multiaddr.html , which returns a not found error.

**Comment by dignifiedquire** [comment]
yeah doc building is broken since the movd to multiformats. need to update the script. 

I saw cargo-travis used in another project, might make things easier.

**Comment by dignifiedquire** [comment]
Fixed :)
