### ISSUE TITLE
Make decapsulate return an error if the protocol is not found

### ISSUE THREAD

**Issue by ProgVal** [multiformats/rust-multiaddr#15]
The doc of `decapsulate` currently reads: “Returns the original if the passed in address is not found”.

Could you change the behavior of `decapsulate` to return an error of the protocol is not found? This way we have a way to know the protocol was not in the multiaddr.
Additionally, it forces users of `decapsulate` to explicitly handle this case when calling it.

**Comment by dignifiedquire** [comment]
Sounds good.

**Comment by deg4uss3r** [comment]
Old issue but I might be able to help here, if this hasn’t been handled yet. :)

**Comment by deg4uss3r** [comment]
Cool! I’ll hold off until that’s merged in.

**Comment by alexander255** [comment]
If this is wanted I can easily add change the final `Ok(self.clone())` line in the `decapsulate` method of my PR to `Err(…)`. I only thought that it may break backcompat, so I didn't do that yet.

**Comment by mxinden** [comment]
Closing here since `decapsule` has been removed in https://github.com/multiformats/rust-multiaddr/pull/40 in favor of basic iteration. Please speak up in case you would like to continue the discussion.
