### ISSUE TITLE
Use `impl From` instead of `trait ToMultiaddr`

### ISSUE THREAD

**Issue by crackcomm** [multiformats/rust-multiaddr#23]
It seems to me that there is too much of `to_*` and `from_*` when it should be enough to use `.into()` and single `impl From`.

**Comment by dignifiedquire** [comment]
Yes makes more sense probably. Though I am not sure, is there any case were you shouldn't use `impl From` or is it okay to use for all conversions?

**Comment by crackcomm** [comment]
Usage of `impl From` should be limited to use cases that are conversions between types.

Traits like `ToString` or `FromStr` should be implemented in cases of deserialization/serialization when input can be invalid but output is always possible.

In this case it seems perfectly fine and more valid to have:

```rust
impl From<Ipv4Addr> for Multiaddr
```
instead of 
```rust
impl ToMultiaddr for Ipv4Addr
```

because as such it is only a type cast.

**Comment by dignifiedquire** [comment]
Thanks for the explanation.

**Comment by tomaka** [comment]
Note that this should be `TryFrom` and not just `From`, because the conversion can return an error.

**Comment by jcc333** [comment]
So I'd love to contribute to this project with the caveat that I'm coming from a c++/scala/haskell background and trying to learn rust so there might be a vocabulary gap. That said I have a couple of questions around the context of this issue:
* Is there a better issue at which I can direct my efforts?
* Is this still an issue to use `From`, or is it `TryFrom` and now the library requires a nightly compiler?
* Is this issue resolved better by a `TryFrom` for each protocol to ensure a homogeneous interface, by `TryFrom` instances for the types which might fail and `From` instances for those types which are assured of success, or by waiting until `TryFrom` becomes stable?

**Comment by mxinden** [comment]
Closing here since this is addressed with https://github.com/multiformats/rust-multiaddr/pull/40. 

@jcc333 let us know in case you would still like to contribute.
