### ISSUE TITLE
Add ipfs and onion support

### ISSUE THREAD

**Issue by dignifiedquire** [multiformats/rust-multiaddr#3]
- [ ] IPFS
- [ ] Onion

**Comment by Dignifiedquire** [comment]
For IPFS I first need to improve rust-multihash as it's missing decoding, as well as base58 handling. I will probably do a new lib from scratch to avoid any license issues.

**Comment by dignifiedquire** [comment]
http://github.com/multiformats/rust-multihash exists now

**Comment by mxinden** [comment]
Closing here as onion support has been added via https://github.com/multiformats/rust-multiaddr/pull/40.
