### ISSUE TITLE
Another rust-multiaddr in rust-libp2p/misc/multiaddr

### ISSUE THREAD

**Issue by ghost** [multiformats/rust-multiaddr#34]
I was wondering about rust-libp2p's bundled version of rust-multiaddr, but it turns out it's already marked for being replaced by the upstream rust-multiaddr: libp2p/rust-libp2p#758

(Filing this issue for visibility)

**Comment by mxinden** [comment]
Closing here since the two are merged with https://github.com/multiformats/rust-multiaddr/pull/40.
