### ISSUE TITLE
src/protocol: Add support for `tls` protocol

### ISSUE THREAD

**Issue by mxinden** [multiformats/rust-multiaddr#47]
https://github.com/multiformats/multiaddr/pull/109/ specifies `tls` as a valid Multiaddr protocol component. The Rust Multiaddr implementation should support it as well.

See https://github.com/multiformats/go-multiaddr/pull/153/ for the corresponding change in the Golang implementation.

**Comment by mxinden** [comment]
@whereistejas would this be something you are interested to take on?

**Comment by whereistejas** [comment]
Hi @mxinden,
Sure! It doesn't look like too much work, I will take on this issue.

**Comment by xprazak2** [comment]
Can this be closed since #48 has been merged?

**Comment by mxinden** [comment]
You are right @xprazak2. Thanks for the ping.
