### ISSUE TITLE
Move to varint for the code bytes

### ISSUE THREAD

**Issue by dignifiedquire** [multiformats/rust-multiaddr#6]

**Comment by Dignifiedquire** [comment]
Not sure how to do this as it seems there is no `varint` implementation for rust that can be used easily.

**Comment by ProgVal** [comment]
Do you mean IPFS' varint? They don't seem to be a spec as of now. https://github.com/multiformats/unsigned-varint

**Comment by mxinden** [comment]
This is addressed with https://github.com/multiformats/rust-multiaddr/pull/40.
