### ISSUE TITLE
tests/lib: Update `impl Arbitrary for Proto`

### ISSUE THREAD

**Issue by mxinden** [multiformats/rust-multiaddr#65]
`Arbitrary` implementation seems to be missing some enum variants.

`Protocol` has `30` variants. `Arbitrary` implementation generates `25`.

Ideally this would be fixed by removing the need to list every `Protocol` variant. Though I can not think of a clean way of doing that. Simply updating the `Arbitrary` implementation seems fine for now.

https://github.com/multiformats/rust-multiaddr/blob/1cfb9239d7447285bfb0f329320945a5e8afabe8/tests/lib.rs#L88-L139

**Comment by mxinden** [comment]
One option would be to use [`variant_count`](https://doc.rust-lang.org/core/mem/fn.variant_count.html) to make sure the above `26` doesn't become outdated. @jxs any other ideas?

**Comment by thomaseizinger** [comment]
> One option would be to use [`variant_count`](https://doc.rust-lang.org/core/mem/fn.variant_count.html) to make sure the above `26` doesn't become outdated. @jxs any other ideas?

That is nightly-only though, right?

**Comment by thomaseizinger** [comment]
We could add a test that only runs on nightly which asserts a constant that we use in the stable tests and run tests on nightly in CI.
